const actionTypes = {
    LOGIN_USER: 'LOGIN_USER',
    LOGIN_USER_SUCCESS: 'LOGIN_USER_LOGIN_USER_SUCCESS',
    LOGIN_USER_LOGIN_USER_FAILURE: 'LOGIN_USER_LOGIN_USER_FAILURE',

    GET_USER_LIST: 'GET_USER_LIST',
    GET_USER_LIST_SUCCESS: 'GET_USER_LIST_SUCCESS',
    GET_USER_LIST_FAILURE: 'GET_USER_LIST_FAILURE',

    UPDATE_USER: 'UPDATE_USER',
    UPDATE_USER_SUCCESS: 'UPDATE_USER_SUCCESS',
    UPDATE_USER_FAILURE: 'UPDATE_USER_FAILURE',

    USER_LOGOUT: 'USER_LOGOUT'
};

export default actionTypes;